# Generated by Django 4.2.1 on 2023-05-20 07:18

from django.db import migrations, models
import fapva.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('code', models.SlugField(blank=True, db_column='Code', default=None, null=True)),
                ('flag', models.FileField(db_column='Flag', default=None, null=True, upload_to=fapva.utils.image_directory_path)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'Services',
            },
        ),
    ]
