# Generated by Django 4.2.1 on 2023-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenumber',
            name='is_paid',
            field=models.BooleanField(db_column='IsPaid', default=False),
        ),
    ]
