# Generated by Django 4.1.7 on 2023-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='access_level',
            field=models.IntegerField(choices=[(500, 'Customer'), (900, 'Super Admin'), (600, 'Operator')], db_column='AccessLevel', default=500),
        ),
    ]
