# Generated by Django 4.2.1 on 2023-05-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved_by_user',
        ),
        migrations.AlterModelTable(
            name='emailverificationlink',
            table='Email_Verification',
        ),
    ]
