# Generated by Django 4.2.1 on 2023-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_column='Username', default=None, max_length=255, null=True),
        ),
    ]
