# Generated by Django 4.2.1 on 2023-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, db_column='Slug', max_length=255, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=255, null=True)),
                ('flag', models.TextField(blank=True, db_column='Flag', null=True)),
                ('dialling_code', models.CharField(blank=True, db_column='DialingCode', max_length=255, null=True)),
                ('currency_code', models.CharField(blank=True, db_column='CurrencyCode', max_length=255, null=True)),
                ('currency_name', models.CharField(blank=True, db_column='CurrencyName', max_length=255, null=True)),
                ('currency_symbol', models.CharField(blank=True, db_column='CurrencySymbol', max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, db_column='LanguageCode', max_length=255, null=True)),
                ('language_symbol', models.CharField(blank=True, db_column='LanguageSymbol', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Countries',
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
