# Generated by Django 4.2.1 on 2023-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_countries_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=False),
        ),
    ]
