# Generated by Django 4.2.1 on 2023-05-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_countries_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='currency_symbol',
        ),
    ]
