# Generated by Django 4.2.1 on 2023-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_countries_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='language_symbol',
        ),
        migrations.AddField(
            model_name='countries',
            name='language_name',
            field=models.CharField(blank=True, db_column='LanguageName', max_length=255, null=True),
        ),
    ]
