# Generated by Django 4.2.1 on 2023-05-19 14:35

from django.db import migrations, models
import fapva.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_countries_language_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.FileField(blank=True, db_column='Flag', null=True, upload_to=fapva.utils.image_directory_path),
        ),
    ]
