# Generated by Django 4.2.1 on 2023-05-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_countries_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='is_deleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
    ]
