# Generated by Django 4.2.1 on 2023-05-23 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('order_id', models.CharField(db_column='OrderId', default=None)),
                ('capture_id', models.CharField(blank=True, db_column='CaptureId', max_length=255, null=True)),
                ('response_json', models.TextField(blank=True, db_column='ResponseJson', null=True)),
                ('payment_channel', models.CharField(db_column='PaymentChannel', default=None, null=True)),
                ('country_id', models.IntegerField(db_column='CountryId', default=0)),
                ('country_name', models.CharField(db_column='CountryName', default=None, null=True)),
                ('number', models.CharField(db_column='Number', default=None, null=True)),
                ('number_id', models.IntegerField(db_column='NumberId', default=None, null=True)),
                ('price', models.FloatField(db_column='Price', default=0)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
