# Generated by Django 4.2.1 on 2023-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expire_at',
            field=models.DateField(db_column='ExpireAt', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country_name',
            field=models.CharField(db_column='CountryName', default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(db_column='Number', default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_column='OrderId', default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(db_column='PaymentChannel', default=None, max_length=255, null=True),
        ),
    ]
