# Generated by Django 4.2.1 on 2023-05-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_expire_at_alter_order_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_number_faulty',
            field=models.BooleanField(db_column='IsNumberFaulty', default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_refunded',
            field=models.BooleanField(db_column='IsRefunded', default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_reason',
            field=models.CharField(db_column='RefundedReason', default=None, max_length=255),
        ),
    ]
