# Generated by Django 4.2.1 on 2023-05-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_is_number_faulty_order_is_refunded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refunded_reason',
            field=models.CharField(db_column='RefundedReason', default=None, max_length=255, null=True),
        ),
    ]
