# Generated by Django 4.2.1 on 2023-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_refunded_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_at',
            field=models.DateTimeField(db_column='ExpireAt', default=None, null=True),
        ),
    ]
