# Generated by Django 4.2.1 on 2023-05-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.BooleanField(blank=True, db_column='Message', default=None, null=True),
        ),
    ]
