# Generated by Django 4.2.1 on 2023-05-27 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_alter_order_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('balance', models.FloatField(db_column='Balance', default=0, null=True)),
                ('is_refunded', models.BooleanField(db_column='IsRefunded', default=True)),
                ('order_placed', models.BooleanField(db_column='OrderPlaced', default=None)),
                ('order', models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, related_name='order_wallet', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserWallet',
            },
        ),
    ]
