# Generated by Django 4.2.1 on 2023-05-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='order',
            field=models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, related_name='order_wallet', to='order.order'),
        ),
    ]
